[package]
name = "raudient"
version = "0.2.0"
authors = ["towangyanqing@gmail.com"]
description = "Rust language version of ipmessager"
repository = "https://github.com/wyq756543431/raudient"
documentation = "https://docs.rs/raudient"
keywords = ["ipmsg", "ipmessager"]
license = "MIT"

[lib]
name = "raudient"

[[bin]]
name = "raudient"
path = "src/bin/raudient.rs"

[dependencies]
chrono = "0.3.0"
hostname = "0.1.3"
local-ip = "0.1.0"
encoding = "0.2.33"
lazy_static = "0.2.8"
log = "0.3"
env_logger = "0.3"
quick-error = "1.2.0"
#nom = "2.2.1"

[dependencies.gtk]
version = "0.1.3"
#git = "https://github.com/gtk-rs/gtk.git"

[dependencies.glib]
version = "0.1.3"
#git = "https://github.com/gtk-rs/glib"