[package]
name = "raudient"
version = "0.4"
authors = ["wangyanqing@langzi.me"]
description = "ipmsg rewrite by rust."
repository = "https://github.com/langzime/raudient"
documentation = "https://docs.rs/raudient"
keywords = ["ipmsg", "ipmessager"]
license = "MIT"
edition = "2021"

[lib]
name = "raudient"

[[bin]]
name = "raudient"
path = "src/bin/raudient.rs"

[dependencies]
chrono = "0.4"
hostname = "0.3"
local-ip = "0.1"
encoding = "0.2"
lazy_static = "1"
log = "0.4"
env_logger = "0.9"
anyhow = "1"
crossbeam-channel = "0.5"
gio = "0.14"
gdk-pixbuf = "0.14"
combine = "4"
human-panic = "1"

[dependencies.gtk]
version = "0.14"

[dependencies.glib]
version = "0.14"
