[package]
name = "raudient"
version = "0.1.0"
authors = ["dujiajiyi"]

[dependencies]
chrono = "0.3.0"
hostname = "0.1.3"
local-ip = "0.1.0"
encoding = "0.2.33"
lazy_static = "0.2.8"
log = "0.3"
env_logger = "0.3"
error-chain = "0.10.0"

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk.git"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"