[package]
name = "raudient"
version = "0.1.0"
authors = ["dujiajiyi"]

[dependencies]
gtk-sys = "0.3.3"
chrono = "0.3.0"
hostname = "0.1.3"
local-ip = "0.1.0"

[dependencies.gtk]
gtk = "0.1.2"
features = ["v3_22"]