import { TextEdit, VerticalBox, ListView } from "std-widgets.slint";
import { ListViewPageAdapter, User } from ".././global.slint";


export component ChatWindow inherits Rectangle {
    min-width: 590px;
    height: 500px;
    in-out property viewport-y <=> lv.viewport-y;
    in-out property viewport-height <=> lv.viewport-height;
    Flickable {
        viewport-width: parent.width;
        width: parent.width;
        height: parent.height;

        public function scroll-down() {
            if (lv.viewport-height <= lv.visible-height ||
                    lv.viewport-y <= -lv.viewport-height + lv.visible-height) {
                return;
            }

            if (lv.viewport-y - lv.visible-height/4 <= -lv.viewport-height) {
                lv.viewport-y = -lv.viewport-height + lv.visible-height;
            } else {
                lv.viewport-y = lv.viewport-y - lv.visible-height/4;
            }
        }

        lv := ListView {
            for data[index] in ListViewPageAdapter.msgs : Rectangle {
                background: darkgrey;
                height: a.preferred-height + 10px;
                width: 580px;
                Image {
                    x: 10px; y: 10px;
                    width: 40px;
                    height: 40px;
                    source: @image-url("../../resources/head.png");
                }
                a := Text {
                    x: 60px; y:10px;
                    font-size: 14px;
                    width: parent.width - 60px;
                    text: "111Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor 防腐剂的负担 Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor";
                    wrap: TextWrap.word-wrap;
                    overflow: TextOverflow.clip;
                    color: yellow;
                }
            }
        }
    }
    
    
}