import { TextEdit, ListView, Button} from "std-widgets.slint";
import { ListViewPageAdapter, User, Logic } from "../global.slint";
import { NoMessage } from "./no_message.slint";

export component LeftMessage inherits Rectangle {
    in-out property<string> m_text;
    in-out property<length> text_lenght <=> t.preferred-height;
    height: max(t.preferred-height + 10px, i.height + 10px + 10px);
    background: lightgreen;
    i := Image {
        x: 10px; y: 10px;
        width: 40px;
        height: 40px;
        source: @image-url("../../resources/head.png");
    }
    t := Text {
        x: 60px; y:10px;
        font-size: 14px;
        width: parent.width - i.width - 10px;
        text: m_text;
        wrap: TextWrap.word-wrap;
        overflow: TextOverflow.clip;
        color: yellow;
    }
}

export component RightMessage inherits Rectangle {
    in-out property<string> m_text;
    in-out property<length> text_lenght <=> t.preferred-height;
    height: max(t.preferred-height + 10px, i.height + 10px + 10px);
    background: green;
    i := Image {
        x: 530px; y: 10px;
        width: 40px;
        height: 40px;
        source: @image-url("../../resources/head.png");
    }
    t := Text {
        x: 10px; y:10px;
        font-size: 14px;
        width: parent.width - i.width - 30px;
        text: m_text;
        wrap: TextWrap.word-wrap;
        overflow: TextOverflow.clip;
        color: yellow;
        horizontal-alignment: right;
    }
}

export component ChatWindow inherits Rectangle {
    min-width: 590px;
    height: 450px;
    in-out property viewport-y <=> lv.viewport-y;
    in-out property viewport-height <=> lv.viewport-height;
    in-out property has_new_msg <=> ListViewPageAdapter.has_new_msg;
    in-out property<bool> is-chats-auto-scroll-down: false;
    changed has_new_msg => {
        debug("has_new_msg changed:");
        debug(has_new_msg);
        if (has_new_msg&&v.is-chats-on-bottom()) {
            debug("xxxxxxx");
            v.scroll-to-bottom();
        }
        has_new_msg = false;
    }
    v := Flickable {
        viewport-width: parent.width;
        width: parent.width;
        height: parent.height;

        public function is-chats-on-bottom() -> bool {
            lv.viewport-y <= -lv.viewport-height + (lv.visible-height * 1.2);
        }

        public function scroll-to-bottom() {
            if (lv.viewport-height <= lv.visible-height) {
                return;
            }
            lv.viewport-y = -lv.viewport-height + lv.visible-height;
        }

        public function scroll-to-top() {
            lv.viewport-y = 0;
        }

        public pure function dyn_height(a_input_height: length, b_input_height: length, is_self: bool) -> length {
            if (!is_self) {
                if (a_input_height >= 60px) {
                    return a_input_height;
                }
            }
            if (is_self) {
                if (b_input_height >= 60px) {
                    return b_input_height;
                }
            }
            debug("dyn_height");
            return 60px;
        }

        lv := ListView {
            for data[index] in ListViewPageAdapter.msgs : Rectangle {
                background: darkgrey;
                height: dyn_height(a.height, b.height, data.is_self);
                width: 580px;
                a := LeftMessage {
                    visible: !data.is_self;
                    m_text: data.text;
                }
                b := RightMessage {
                    visible: data.is_self;
                    m_text: data.text;
                }
            }
        }
    }
}

export component SendBox inherits Rectangle {
    in-out property <string> pre_send_text <=> te.text;
    te := TextEdit {
        font-size: 14px;
        width: parent.width;
        height: parent.height;
        text: "";
        wrap: word-wrap;
    }
}

export component Right inherits Rectangle {
    in-out property <string> pre_send_text <=> sb.pre_send_text;
    VerticalLayout {
        visible: ListViewPageAdapter.user_id != "";
        ChatWindow {
        }
        sb := SendBox {
            background: lightgrey;
            border-color: grey;
        }
        HorizontalLayout {
            alignment: end;
            Button {
                text: "发送";
                width: 150px;
                primary: true;
                enabled: pre_send_text != "";
                clicked => {
                    if (ListViewPageAdapter.user_id != "") {
                        Logic.send_msg(ListViewPageAdapter.user_id, ListViewPageAdapter.user_name, 1, pre_send_text);
                        pre_send_text = "";
                    }
                }
            }
        }
    }

    NoMessage {
        visible: ListViewPageAdapter.user_id == "";
    }
}



