import { ListView } from "std-widgets.slint";
import { ListViewPageAdapter, User } from "../global.slint";


export global UserListAdapter {
    callback change_selected_user(string);
}

export component UserList inherits Rectangle {
    background: #dcdcdd;
    min-width: 200px;

    Flickable {
        viewport-width: parent.width;
        width: parent.width;
        height: parent.height;
        lv := ListView {
            for data in ListViewPageAdapter.users: Rectangle {
                height: 60px;
                background: data.active? #c4c4c4:#dcdcdd;
                width: parent.width;
                Image {
                    x: 10px; y: 10px;
                    width: 40px;
                    height: 40px;
                    source: @image-url("../../resources/head.png");
                }
                Rectangle {
                    visible: data.unread_count > 0;
                    background: red;
                    x: 45px;
                    y: 5px;
                    width: 10px;
                    height: 10px;
                    border-radius: 5px;
                }
                VerticalLayout {
                    padding-top: 15px;
                    Text {
                        x: 60px;
                        // padding-top: 10px;
                        text: data.name;
                        // color: data.color;
                        color: green;

                    }
                    Text {
                        x: 60px;
                        text: data.userId;
                        // color: data.color;
                    }
                }
                area := TouchArea {
                    width: parent.width;
                    height: parent.height;
                    clicked => {
                        UserListAdapter.change_selected_user(data.userId);
                    }

                }
            }
        }
    }

}