refresh_rate: 5 seconds

appenders:
  console:
    kind: console
    encoder:
      pattern: "{d(%+)(local)} [{t}] {h({l})} {M}:{m}{n}"
    filters:
      - kind: threshold
        level: debug
root:
  level: debug
  appenders:
    - console