import { Button, VerticalBox, ListView, HorizontalBox } from "std-widgets.slint";
import { ChatWindow, ToolBar, UserList, UserListAdapter, Right } from "./views/index.slint";
import { ROOT_GLOBAL, ListViewPageAdapter, User, Logic } from "./global.slint";

export { ListViewPageAdapter, User, Logic }
export { UserList, UserListAdapter }

export component IpmsgUI inherits Window {
    min-width: ROOT_GLOBAL.window-width;
    min-height: ROOT_GLOBAL.window-height;
    title: @tr("ipmsg");
    // no-frame: true;
    public function scroll-to-bottom() {
        r.scroll-to-bottom();
    }
    HorizontalLayout {
        ToolBar {}
        UserList {}
        r := Right {}
    }
}