@rust-attr(derive(serde::Serialize, serde::Deserialize))
export struct User  { userId: string, name: string, active: bool, last_beat_time: string, on_line: bool, unread_count: int}

@rust-attr(derive(serde::Serialize, serde::Deserialize))
export struct Msg  { userId: string, name: string, image_url: string, text: string, is_self: bool}

export global ListViewPageAdapter  {
    in property <[User]> users: [];
    in property <[Msg]> msgs: [];
    in property <string> user_id: "";
    in property <string> user_name: "";
}

export global ROOT_GLOBAL {
    in-out property <length> window-width: 850px;
    in-out property <length> window-height: 620px;
    in-out property <length> font-size: 16px;
    in-out property <length> padding: 0px;
}

export global Logic {
    callback send_msg(string, string, int, string);
}