import { ListView } from "std-widgets.slint";
import { ListViewPageAdapter, User } from "global.slint";


export global UserListClick {
    pure callback user_list_click(string);
}

export component UserList inherits Rectangle {
    background: #dcdcdd;
    min-width: 200px;
    callback change_selected_user(string);
    ListView {
        for data in ListViewPageAdapter.users: Rectangle {
            height: 60px;
            background: data.active? #c4c4c4:#dcdcdd;
            width: parent.width;
            Image {
                x: 10px; y: 10px;
                width: 40px;
                height: 40px;
                source: @image-url("../resources/head.png");
            }
            VerticalLayout {
                padding-top: 15px;
                Text {
                    x: 60px;
                    // padding-top: 10px;
                    text: data.name;
                    // color: data.color;
                    color: green;
                    
                }
                Text {
                    x: 60px;
                    text: data.userId;
                    // color: data.color;
                }
            }
            area := TouchArea {
                width: parent.width;
                height: parent.height;
                clicked => {
                    root.change_selected_user(data.userId);
                }
                
            }
        }

    }
}